### ISSUE TITLE
[功能请求] 希望可以增加站点切换的功能

### ISSUE THREAD

**Issue by fxxxjew** [lanyeeee/manhuagui-downloader-wails#11]
### 原因

手机版m.manhuagui.com在大陆部分地区可以使用但其他不能。如果可以切换手机版进行解析则可以省去代理。

### 功能简述

切换手机版解析

### 功能逻辑

添加地址切换，切换时使用手机版链接

**Comment by lanyeeee** [comment]
刚才看了一下，手机版网页与电脑版的差异挺大的  

要实现这个功能，大概有30%的代码要重构  
而且如果以后漫画柜的网页结构发生变动，我将不得不维护两套代码，增加了维护的成本    

考虑到这个功能的目的是**可能可以省去代理**，这样的投入相对收益显得不太合理(~~我这里即使是手机版也要用代理~~)
