### ISSUE TITLE
[Bug] 漫画导出总是自行退出，无法完成导出

### ISSUE THREAD

**Issue by myacera100** [lanyeeee/manhuagui-downloader-wails#12]
### 问题描述

Win11，下载完漫画后，无论选择部分章节还是全选，导出漫画均会导致程序退出；查看导出目录，仅有少量完成导出

### 预期行为

导出目录和缓存目录更改后，再次启动程序应能复现

### 实际行为

无法保存目录设置，再次启动程序，设置依然是默认值

### 工具版本号

v0.9

**Comment by lanyeeee** [comment]
导出哪部漫画，哪个章节会这样

**Comment by myacera100** [comment]
无论是批量导出，还是章节导出，都会FC
![屏幕截图 2024-11-06 214556](https://github.com/user-attachments/assets/dd18646e-380d-4067-b7df-6569e11e5ac9)

**Comment by myacera100** [comment]
而且也无法保存目录设置，似乎没有保存按钮，正常退出后也无法保存这些设置

**Comment by lanyeeee** [comment]
导出pdf自行退出的问题无法复现，我这边能正常导出《天子传奇1姬发篇》
你试试能不能只导出一话，像这样
![image](https://github.com/user-attachments/assets/a5a2ed1c-a7e7-4877-a114-4f12581d7820)



另外，无法保存目录设置是因为软件没有配置文件，不会保存任何东西
如果真的需要这个功能请另外开`功能请求issue`

**Comment by myacera100** [comment]
看来是我这边的问题，我自己再查查

**Comment by lanyeeee** [comment]
只导出一话可以吗？
如果可以的话大概率是导出多话的时候爆内存了

**Comment by myacera100** [comment]
一话也是强退
