### ISSUE TITLE
[Bug] 修改我！

### ISSUE THREAD

**Issue by wesleyx2** [lanyeeee/manhuagui-downloader-wails#13]
### 问题描述

https://www.manhuagui.com/comic/18369/
这部漫画获取不到列表
只能看到漫画名

### 预期行为

获取列表

### 实际行为

获取不到列表

### 截图或录屏

![QQ截图20241119095636](https://github.com/user-attachments/assets/05331f8e-517c-48f4-8ece-cec59cbce4af)

### 工具版本号

0.9

**Comment by lanyeeee** [comment]
![image](https://github.com/user-attachments/assets/3310a90a-1131-49f6-a6c5-6a80d84be662)

**Comment by wesleyx2** [comment]
但是这个漫画我在网页版可以看啊
![Uploading QQ截图20241119100403.png…]()

**Comment by wesleyx2** [comment]
好像这会又可以了 难道是什么缓存问题……

**Comment by lanyeeee** [comment]
魔法线路的问题吧，我用泰国也能看到

**Comment by wesleyx2** [comment]
应该是不同线路负载均衡的问题 可能是屏蔽了某个区域 然后又切换了一个另一个可以看的区域的魔法的缘故
