### ISSUE TITLE
[Bug]无法保存缓存目录

### ISSUE THREAD

**Issue by wesleyx2** [lanyeeee/manhuagui-downloader-wails#14]
### 问题描述

无法保存缓存目录 每次关闭程序后都会变回默认目录

### 预期行为

应该保存修改后目录

### 实际行为

程序关闭后恢复了默认目录

### 截图或录屏

![QQ截图20241119100122](https://github.com/user-attachments/assets/ac155f50-87de-4a52-a162-1be2dae79663)
![QQ截图20241119100110](https://github.com/user-attachments/assets/41de8c99-d975-4e74-b67b-a2ce468d7b12)

### 工具版本号

0.9

**Comment by lanyeeee** [comment]
当时开发时没考虑配置文件，所以“没有记忆”，所以这是符合预期的
要加配置文件改的代码有点多
漫画柜也不让大批量下载，所以默认路径里也不会有多少漫画，自己手动搬一下吧

**Comment by wesleyx2** [comment]
好的 不是大问题 就是点了几次一直保存不了觉得是不是有问题
