### ISSUE TITLE
[Bug] 修改我！导出时闪退

### ISSUE THREAD

**Issue by QcodeU** [lanyeeee/manhuagui-downloader-wails#15]
### 问题描述

点击导出漫画时瞬间闪退，并且生成的pdf文件为0kb，稳定触发

### 预期行为

正常情况下应该是生成可打开的pdf文件

### 实际行为

只要点击导出就会闪退，并不能生成可用的pdf文件

### 工具版本号

v0.9

**Comment by lanyeeee** [comment]
我没办法修，因为我无法复现，我能正常导出，可能是[本项目依赖的pdf库](https://github.com/pdfcpu/pdfcpu)无法在你的环境上正常运行？

**Comment by lanyeeee** [comment]
这个需求许多第三方工具都能做到，例如https://github.com/wmjordan/PDFPatcher
