### ISSUE TITLE
[Bug] 点击漫画进入列表后闪退

### ISSUE THREAD

**Issue by UCPRER** [lanyeeee/manhuagui-downloader-wails#5]
### 问题描述

0.8版本搜索漫画后，点击一个漫画后，等列表出现后会闪退

### 预期行为

不闪退

### 实际行为

0.8版本搜索漫画后，点击一个漫画后，等列表出现后会闪退

### 截图或录屏

![BE9BKW_N{1}4DVP8~Q{7O6B](https://github.com/user-attachments/assets/757103a8-4a59-40be-9b08-8781fd26de85)

### 工具版本号

v0.8

### 其他

免安装和安装版都稳定复现，v0.4版本没这个问题

**Comment by lanyeeee** [comment]
排查了一下，这个问题是把依赖的 [go-webview2](https://github.com/wailsapp/go-webview2) 从`v1.0.10`升级到`v1.0.11`导致的
把它的版本回退到 `v1.0.10` 就好了😑😑😑
这个问题只存在于0.8版本，且已在0.9版本修复
