### ISSUE TITLE
SearchComicByKeyword: unexpected status code: 403

### ISSUE THREAD

**Issue by liuyuting0525** [lanyeeee/manhuagui-downloader-wails#9]
### 问题描述

搜索不到任何漫画

### 预期行为

给链接也不行

### 实际行为

SearchComicByKeyword: unexpected status code: 403
报错上面这条

### 工具版本号

0.9

**Comment by lanyeeee** [comment]
中国大陆访问 [漫画柜](https://www.manhuagui.com/) 是需要代理的

如果你没有使用代理，请打开代理再重启软件试试

如果你已经使用了代理
试试网页能不能访问 [漫画柜](https://www.manhuagui.com/) 并搜索到相关漫画
如果网页可以访问，大概率是自动检测的代理地址出错了，可以前往 **设置** -> **代理地址** 根据你的代理设置手动调整
如果网页不能访问，大概率是这条代理的线路被漫画柜屏蔽了，换条线路试试，换到能访问网页的线路后，再重启软件试试

**Comment by liuyuting0525** [comment]
网页可以访问的，也开启了代理

**Comment by liuyuting0525** [comment]
解决问题了，谢谢

**Comment by xuxuxuxuwu** [comment]
> 解决了，谢谢

想咨询下您怎么解决的
